"""RhoDyn core package."""

from rhodyn.backend_core import (
    AnalysisBundle,
    FileJobStore,
    JobRetentionPolicy,
    StoredJob,
    build_analysis_bundle,
    compare_endpoint_models,
    decide_coupling_table,
    export_markdown_report,
    run_backend_operation,
    score_residence_table,
    summarize_reserve_table,
    validate_table,
    write_analysis_bundle,
)
from rhodyn.compare import ModelFit, rank_model_fits
from rhodyn.coupling import (
    EquivalenceDecision,
    TostDecision,
    equivalence_from_interval,
    one_sample_tost,
    rope_decision,
    rope_mass,
    two_sample_welch_tost,
)
from rhodyn.ctc import (
    CTC_LINEAGE_SIGNAL_CHOICES,
    CTC_SIGNAL_CHOICES,
    CtcFeatureRecord,
    CtcLineageRecord,
    CtcTiffImage,
    ctc_features_to_trajectory_records,
    ctc_lineage_coverage_issues,
    ctc_lineage_to_trajectory_records,
    ctc_mask_to_feature_records,
    ctc_sequence_replicate,
    ctc_track_cell_id,
    read_ctc_feature_csv,
    read_ctc_lineage,
    read_uncompressed_grayscale_tiff,
    write_trajectory_csv,
)
from rhodyn.extras import MissingOptionalDependency, OptionalExtra, extra_plan, require_extra
from rhodyn.models import ControllerParams, simulate_controller
from rhodyn.plots import (
    plot_coupling_interval,
    plot_model_residuals,
    plot_reserve_summary,
    plot_residence_trace,
    plot_sensitivity_curve,
)
from rhodyn.residence import ResidenceWindow, score_trace
from rhodyn.results import (
    CouplingResult,
    GroupMetadata,
    ModelComparisonResult,
    ResidenceResult,
    ReserveResult,
    ResultProvenance,
    SensitivityCurveResult,
    SensitivityPoint,
    UncertaintyInterval,
    coupling_result_from_decision,
    coupling_result_from_tost,
    model_comparison_result_from_fits,
    residence_result_from_summary,
)
from rhodyn.schema import CouplingIntervalRecord, EndpointRecord, ReserveRecord, TrajectoryRecord, schema_specs
from rhodyn.sensitivity import (
    linear_grid,
    residence_window_grid,
    score_records_window_sensitivity,
    score_trace_window_sensitivity,
)
from rhodyn.uncertainty import BootstrapResult, PermutationResult, bootstrap_interval, permutation_test

__all__ = [
    "ControllerParams",
    "BootstrapResult",
    "AnalysisBundle",
    "FileJobStore",
    "JobRetentionPolicy",
    "StoredJob",
    "CTC_LINEAGE_SIGNAL_CHOICES",
    "CTC_SIGNAL_CHOICES",
    "CouplingIntervalRecord",
    "CouplingResult",
    "CtcFeatureRecord",
    "CtcLineageRecord",
    "CtcTiffImage",
    "EndpointRecord",
    "EquivalenceDecision",
    "GroupMetadata",
    "MissingOptionalDependency",
    "ModelFit",
    "ModelComparisonResult",
    "OptionalExtra",
    "PermutationResult",
    "ResidenceResult",
    "ResidenceWindow",
    "ReserveRecord",
    "ReserveResult",
    "ResultProvenance",
    "SensitivityCurveResult",
    "SensitivityPoint",
    "TostDecision",
    "TrajectoryRecord",
    "UncertaintyInterval",
    "bootstrap_interval",
    "build_analysis_bundle",
    "compare_endpoint_models",
    "coupling_result_from_decision",
    "coupling_result_from_tost",
    "ctc_features_to_trajectory_records",
    "ctc_lineage_coverage_issues",
    "ctc_lineage_to_trajectory_records",
    "ctc_mask_to_feature_records",
    "ctc_sequence_replicate",
    "ctc_track_cell_id",
    "equivalence_from_interval",
    "extra_plan",
    "decide_coupling_table",
    "export_markdown_report",
    "linear_grid",
    "model_comparison_result_from_fits",
    "one_sample_tost",
    "permutation_test",
    "plot_coupling_interval",
    "plot_model_residuals",
    "plot_reserve_summary",
    "plot_residence_trace",
    "plot_sensitivity_curve",
    "rank_model_fits",
    "read_ctc_feature_csv",
    "read_ctc_lineage",
    "read_uncompressed_grayscale_tiff",
    "residence_result_from_summary",
    "residence_window_grid",
    "require_extra",
    "rope_decision",
    "rope_mass",
    "schema_specs",
    "run_backend_operation",
    "score_records_window_sensitivity",
    "score_residence_table",
    "score_trace",
    "score_trace_window_sensitivity",
    "simulate_controller",
    "summarize_reserve_table",
    "two_sample_welch_tost",
    "validate_table",
    "write_analysis_bundle",
    "write_trajectory_csv",
]

__version__ = "0.1.0"
